#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
_013_AlignBot.py — Build per-chain MSAs and alignment maps from residue maps.

USAGE
-----
    python src/_013_AlignBot.py config/Run0010_....yml

CONFIG (YAML)
-------------
You can specify the aligner either with the legacy flat key:
    alignment_algo: auto   # one of: auto | mafft | clustalo | muscle | none

…or with a nested key (optional convenience):
    alignment:
      tool: auto

BEHAVIOR (this version)
-----------------------
Inputs (from previous step _012_ResidueMapBot.py):
    input/residue_maps/<SimID>/*_residue_map.csv
      Required columns: chain_id, chain_pos, aa

This script creates ONE canonical FASTA per chain (kept):
    input/alignments/<SimID>/<SimID>_<ChainID>_chains.fasta         (KEPT)

Then it runs the selected aligner and writes per-tool outputs here:
    input/alignments/<SimID>/<effective_tool>/<SimID>_<ChainID>_chains_align_out.fasta
    input/alignments/<SimID>/<effective_tool>/<SimID>_<ChainID>_align_map.csv
    input/alignments/<SimID>/<effective_tool>/<SimID>_summary.json

Notes:
- We no longer create the redundant “…_align_in.fasta” files under the per-tool
  directory. The “*_chains.fasta” files are the single source of truth for inputs.
- The per-tool subfolder name reflects the actual (effective) tool used.
  (e.g., if algo=auto and MAFFT is found → “mafft”)
"""

from __future__ import annotations

import os
import re
import sys
import yaml
import json
import shutil
import subprocess
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Dict, List, Tuple, Optional

import pandas as pd
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

# Optional: friendlier perms if your pipeline sometimes runs as root
try:
    from perm_helper import ensure_writable, set_owner_and_perms
except Exception:
    def ensure_writable(_): pass
    def set_owner_and_perms(_p, mode=0o664): pass

# ------------------------------
# Config & paths
# ------------------------------

# Where we store canonical chain FASTAs and per-tool outputs
ALIGN_BASE_DIR = Path("input") / "alignments"

# Where residue maps live (generated by _012_ResidueMapBot.py)
RESMAPS_ROOT   = Path("input") / "residue_maps"

# Supported aligner options (including “auto” resolver and “none” passthrough)
SUPPORTED = {"auto", "mafft", "clustalo", "muscle", "none"}

# ------------------------------
# Small helpers
# ------------------------------

def _parse_sim_id_from_runfile(path: Path) -> str:
    """
    From a run file like 'Run0010_...' produce '0010'.
    Fallback: first 4 consecutive digits; if none, use the stem.
    """
    name = path.stem
    m = re.match(r"Run(\d{4})[_\-]", name, flags=re.IGNORECASE)
    if m:
        return m.group(1)
    m2 = re.search(r"(\d{4})", name)
    return m2.group(1) if m2 else name

def _which(name: str) -> Optional[str]:
    """shutil.which wrapper."""
    return shutil.which(name)

def _pick_binary(algo: str) -> tuple[str, str]:
    """
    Return (tool_name, full_path_to_executable).
    If algo=='auto', try mafft → clustalo → muscle (first one found wins).
    """
    algo = algo.lower()
    order = ["mafft", "clustalo", "muscle"] if algo == "auto" else [algo]
    for tool in order:
        candidates = {
            "mafft":    ["mafft"],
            "clustalo": ["clustalo", "clustal-omega", "clustalomega"],
            "muscle":   ["muscle"],
        }.get(tool, [])
        for c in candidates:
            p = _which(c)
            if p:
                return tool, p
    raise FileNotFoundError(
        f"No alignment binary found for '{algo}'. Tried: {', '.join(order)}. "
        f"Install e.g. `conda install -c bioconda mafft`."
    )

def _effective_algo_label(algo: str) -> str:
    """
    Resolve the actual tool label used. For 'none', return 'none'.
    For 'auto' or a specific tool, return the concrete tool name (mafft/clustalo/muscle),
    based on availability in PATH.
    """
    if algo.lower() == "none":
        return "none"
    tool, _ = _pick_binary(algo)  # may raise if nothing installed and algo!='none'
    return tool

# ------------------------------
# IO: residue maps → chain FASTAs (canonical)
# ------------------------------

@dataclass
class ChainSeq:
    job: str                # job identifier derived from residue_map filename
    chain: str              # A / B / C / ...
    seq: str                # amino-acid string
    res_index_list: List[int]  # native residue indices (chain_pos) per AA, in order

def _collect_residue_maps(sim_id: str) -> List[Path]:
    """Find all *_residue_map.csv for a given SimID."""
    d = RESMAPS_ROOT / sim_id
    if not d.is_dir():
        raise FileNotFoundError(f"No residue maps at {d}")
    files = sorted(p for p in d.glob("*_residue_map.csv") if p.is_file())
    if not files:
        raise FileNotFoundError(f"No *_residue_map.csv under {d}")
    return files

def _job_label_from_resmap_filename(p: Path) -> str:
    """e.g. '0010-01_residue_map.csv' → '0010-01'"""
    return p.stem.replace("_residue_map", "")

def _load_chainseqs_for_sim(sim_id: str) -> Dict[str, List[ChainSeq]]:
    """
    Return dict chain_label -> list of ChainSeq (one per job that has that chain).
    Each ChainSeq carries the sequence (derived from 'aa' column) and a parallel list
    of residue indices (chain_pos) to map aligned positions back to native indices.
    """
    chain_to_records: Dict[str, List[ChainSeq]] = {}
    for csv_path in _collect_residue_maps(sim_id):
        job = _job_label_from_resmap_filename(csv_path)
        df = pd.read_csv(csv_path)
        required = {"chain_id", "chain_pos", "aa"}
        if not required.issubset(df.columns):
            raise KeyError(f"{csv_path} missing required columns (need {sorted(required)}).")
        for chain in sorted(df["chain_id"].unique()):
            sub = df[df["chain_id"] == chain].copy()
            sub = sub.sort_values("chain_pos", kind="mergesort")
            seq = "".join(sub["aa"].astype(str).str.upper().tolist())
            idxs = sub["chain_pos"].astype(int).tolist()
            rec = ChainSeq(job=job, chain=str(chain), seq=seq, res_index_list=idxs)
            chain_to_records.setdefault(str(chain), []).append(rec)
    return chain_to_records

def _write_per_chain_fastas(sim_id: str,
                            chain_to_records: Dict[str, List[ChainSeq]],
                            chains_dir: Path) -> Dict[str, Path]:
    """
    Write one canonical FASTA per chain under:
        input/alignments/<SimID>/<SimID>_<Chain>_chains.fasta

    These are the ONLY input FASTAs we keep. Returns {chain: fasta_input_path}.
    """
    chains_dir.mkdir(parents=True, exist_ok=True)
    result: Dict[str, Path] = {}
    for chain, recs in chain_to_records.items():
        records: List[SeqRecord] = []
        for rec in recs:
            # Header embeds the job id, chain, and length → used later to map back to native indices
            header = f"job={rec.job}|chain={chain}|len={len(rec.seq)}"
            records.append(SeqRecord(Seq(rec.seq), id=header, description=""))
        fp = chains_dir / f"{sim_id}_{chain}_chains.fasta"
        with open(fp, "w", encoding="utf-8") as fh:
            SeqIO.write(records, fh, "fasta")
        set_owner_and_perms(fp)
        result[chain] = fp
    return result

# ------------------------------
# Run alignment via subprocess
# ------------------------------

def _run_alignment_to_fasta(fasta_in: Path, algo: str, out_dir: Path) -> Path:
    """
    Run the chosen aligner and return aligned FASTA path (always written into out_dir).

    Naming:
        input   = <SimID>_<Chain>_chains.fasta
        output  = <out_dir>/<SimID>_<Chain>_chains_align_out.fasta

    Special cases:
        - If only one sequence is present or algo=='none', we just copy the input as output.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    # Output filename is based on the input stem to remain self-descriptive
    aln_out = out_dir / f"{fasta_in.stem}_align_out.fasta"

    # Count sequences to decide if alignment is meaningful
    nseq = sum(1 for _ in SeqIO.parse(str(fasta_in), "fasta"))
    if nseq <= 1 or algo.lower() == "none":
        shutil.copy2(fasta_in, aln_out)
        set_owner_and_perms(aln_out)
        return aln_out

    tool, exe = _pick_binary(algo)

    if tool == "mafft":
        cmd = [exe, "--auto", str(fasta_in)]
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if proc.returncode != 0:
            raise RuntimeError(f"MAFFT failed ({proc.returncode}). STDERR:\n{proc.stderr}")
        aln_out.write_text(proc.stdout, encoding="utf-8")
        set_owner_and_perms(aln_out)
        return aln_out

    if tool == "clustalo":
        cmd = [exe, "-i", str(fasta_in), "-o", str(aln_out), "--force", "--outfmt=fasta"]
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if proc.returncode != 0:
            raise RuntimeError(f"Clustal Omega failed ({proc.returncode}). STDERR:\n{proc.stderr}")
        set_owner_and_perms(aln_out)
        return aln_out

    if tool == "muscle":
        # MUSCLE v5 prefers -align/-output; v3 uses -in/-out. Try v5 first, then fallback.
        cmd_v5 = [exe, "-align", str(fasta_in), "-output", str(aln_out)]
        proc = subprocess.run(cmd_v5, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if proc.returncode == 0:
            set_owner_and_perms(aln_out)
            return aln_out
        cmd_v3 = [exe, "-in", str(fasta_in), "-out", str(aln_out)]
        proc2 = subprocess.run(cmd_v3, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if proc2.returncode != 0:
            raise RuntimeError(
                "MUSCLE failed.\n"
                f"v5 STDERR:\n{proc.stderr}\n"
                f"v3 STDERR:\n{proc2.stderr}\n"
            )
        set_owner_and_perms(aln_out)
        return aln_out

    raise ValueError(f"Unsupported tool: {tool}")

# ------------------------------
# Alignment → native index map
# ------------------------------

def _parse_header_job_chain(header: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Parse 'job=...|chain=...|...' headers created by _write_per_chain_fastas.
    Returns (job, chain).
    """
    job = chain = None
    for part in header.split("|"):
        if "=" in part:
            k, v = part.split("=", 1)
            if k == "job":
                job = v
            elif k == "chain":
                chain = v
    return job, chain

def _build_alignment_map_for_chain(aligned_fasta: Path,
                                   chain_records: List[ChainSeq],
                                   out_csv: Path) -> None:
    """
    Emit CSV with columns: chain, aln_pos, job, res_idx, aa_aln

    - chain: chain label ('A', 'B', …)
    - aln_pos: 1-based position in the aligned sequence
    - job: original job label for each sequence row
    - res_idx: native residue index (chain_pos from residue map) or NA if gap
    - aa_aln: aligned character at aln_pos for that job (AA or '-')
    """
    # Map (job, chain) -> native residue index list (serial order)
    residx: Dict[Tuple[str, str], List[int]] = {
        (rec.job, rec.chain): rec.res_index_list for rec in chain_records
    }

    records = list(SeqIO.parse(str(aligned_fasta), "fasta"))

    # Build per-record state: the aligned string and a cursor into native indices
    state: Dict[Tuple[str, str], Dict[str, object]] = {}
    for rec in records:
        job, chain = _parse_header_job_chain(rec.id)
        key = (job, chain)
        if key not in residx:
            raise KeyError(f"Aligned header {rec.id} not found among input sequences.")
        state[key] = {"aln": str(rec.seq), "cursor": 0, "job": job, "chain": chain}

    rows: List[Dict[str, object]] = []
    aln_len = max(len(s["aln"]) for s in state.values())
    for i in range(aln_len):  # 0-based in code → 1-based in output
        for key, st in state.items():
            job, chain = st["job"], st["chain"]
            aa = st["aln"][i] if i < len(st["aln"]) else "-"
            if aa == "-":
                res_idx = None
            else:
                cur = st["cursor"]
                li = residx[(job, chain)]
                res_idx = li[cur] if cur < len(li) else None
                st["cursor"] = cur + 1
            rows.append({
                "chain": chain,
                "aln_pos": i + 1,
                "job": job,
                "res_idx": res_idx,
                "aa_aln": aa
            })

    out_csv.parent.mkdir(parents=True, exist_ok=True)
    ensure_writable(out_csv)
    pd.DataFrame(rows).to_csv(out_csv, index=False)
    set_owner_and_perms(out_csv)

# ------------------------------
# Orchestration
# ------------------------------

@dataclass
class Summary:
    sim_id: str
    config_path: str
    algo: str               # as requested in YAML (auto/mafft/...)
    effective_algo: str     # resolved tool name actually used
    outputs: Dict[str, Dict[str, str]]  # chain -> {msa_in, msa_out, map_csv}
    binaries_checked: List[str]

def run_from_config(cfg_path: str) -> Summary:
    """Main entry used by CLI and importers; returns a Summary dataclass."""
    cfg_p = Path(cfg_path)
    if not cfg_p.is_file():
        raise FileNotFoundError(f"Config not found: {cfg_p}")

    with open(cfg_p, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh) or {}

    # Read aligner choice.
    # Prefer legacy flat key (what existing runs expect), but also accept nested form.
    algo = str(
        cfg.get("alignment_algo",
                (cfg.get("alignment") or {}).get("tool", "auto"))
    ).lower()
    if algo not in SUPPORTED:
        raise ValueError(f"alignment_algo must be one of {sorted(SUPPORTED)}")

    # Determine simulation ID from filename (Run0010_* → '0010')
    sim_id = _parse_sim_id_from_runfile(cfg_p)

    # Resolve the effective aligner to use (and validate availability)
    effective = _effective_algo_label(algo)  # may raise if nothing installed and algo!='none'
    print(f"[AlignBot] sim_id = {sim_id}  |  algo = {algo}  |  effective = {effective}")

    # Load sequences grouped by chain
    chain_to_records = _load_chainseqs_for_sim(sim_id)
    chains = sorted(chain_to_records.keys())
    if not chains:
        raise RuntimeError("No chains discovered in residue maps.")

    # Directories:
    #  - chains_dir: canonical per-chain input FASTAs (kept)
    #  - out_dir: per-tool outputs (aligned FASTAs + maps + summary)
    chains_dir = ALIGN_BASE_DIR / sim_id
    out_dir    = ALIGN_BASE_DIR / sim_id / effective
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write canonical per-chain FASTAs once (…/<SimID>/<SimID>_<Chain>_chains.fasta)
    fasta_inputs = _write_per_chain_fastas(sim_id, chain_to_records, chains_dir)

    # Collect which binaries were found (diagnostic)
    outputs: Dict[str, Dict[str, str]] = {}
    bins_checked: List[str] = []
    if algo != "none":
        for nm in ["mafft", "clustalo", "clustal-omega", "clustalomega", "muscle"]:
            p = _which(nm)
            if p: bins_checked.append(f"{nm}={p}")

    # For each chain, align and build the alignment→native map CSV
    for chain in chains:
        fasta_in = fasta_inputs[chain]
        print(f"[AlignBot] Aligning chain {chain} from {fasta_in} …")
        msa_out = _run_alignment_to_fasta(fasta_in, algo, out_dir)
        map_csv = out_dir / f"{sim_id}_{chain}_align_map.csv"
        _build_alignment_map_for_chain(msa_out, chain_to_records[chain], map_csv)
        outputs[chain] = {
            # Keep key name for downstream compatibility; now points to the chains FASTA
            "msa_in": str(fasta_in),
            "msa_out": str(msa_out),
            "map_csv": str(map_csv),
        }
        print(f"[AlignBot]  → MSA IN : {fasta_in}")
        print(f"[AlignBot]  → MSA OUT: {msa_out}")
        print(f"[AlignBot]  → Map    : {map_csv}")

    # Write a per-run summary JSON into the per-tool directory
    summary = Summary(sim_id=sim_id,
                      config_path=str(cfg_p),
                      algo=algo,
                      effective_algo=effective,
                      outputs=outputs,
                      binaries_checked=bins_checked)
    out_summary = out_dir / f"{sim_id}_summary.json"
    with open(out_summary, "w", encoding="utf-8") as fh:
        json.dump(asdict(summary), fh, indent=2)
    set_owner_and_perms(out_summary)

    print(f"[AlignBot] Done. Summary: {out_summary}")
    return summary

def main():
    if len(sys.argv) != 2:
        print("Usage: python src/_013_AlignBot.py config/RunXXXX_....yml")
        sys.exit(1)
    run_from_config(sys.argv[1])

if __name__ == "__main__":
    main()
